name: Android CI

on:
  push:
    branches:
      - main  # Запуск при пушах в ветку main
  pull_request:
    branches:
      - main  # Запуск для pull request, целевой веткой которых является main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'  # Версия JDK, используемая вашим проектом. Убедитесь, что она соответствует вашим требованиям.

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload artifact
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: bullshit.apk
          path: app/build/outputs/apk/debug/app-debug.apk
